version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: racing
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      network: host
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/racing
      JWT_SECRET: supersecret
      PORT: 5000
      UPLOAD_DIR: uploads
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
      - ./database:/usr/src/database:ro
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      network: host  # 👈 This enables host networking during image build
      args:
        - VITE_API_URL=${VITE_API_URL}
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./frontend/public/images:/usr/src/app/dist/images
    depends_on:
      - backend
    ports:
      - "5173:4173"

volumes:
  db-data:

networks:
  default:
    driver: bridge
