version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: racing
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      network: host
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/racing
      JWT_SECRET: supersecret
      PORT: 5000
      UPLOAD_DIR: uploads
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      network: host  # 👈 This enables host networking during image build
    environment:
      VITE_API_URL: http://localhost:5000/api #Change this to your server IP
    depends_on:
      - backend
    ports:
      - "5173:4173"

volumes:
  db-data:

networks:
  default:
    driver: bridge
