version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: racing
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/racing
      JWT_SECRET: supersecret
      PORT: 5000
      UPLOAD_DIR: uploads
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    ports:
      - "5173:4173"

volumes:
  db-data:
